import {base,shots,check,setup,signup,goto,matrix,finish} from './r9-helpers.mjs';
const {browser,context,page}=await setup();
try {
  await goto(page,'/settings');
  check('Settings protected',new URL(page.url()).pathname==='/login' && new URL(page.url()).searchParams.get('next')==='/settings');
  const user=await signup(context,'settings');
  let meCalls=0,logoutCalls=0;
  page.on('request',r=>{if(r.url().endsWith('/api/auth/me')) meCalls++;if(r.url().endsWith('/api/auth/logout')&&r.method()==='POST')logoutCalls++;});
  await goto(page,'/settings');
  check('One shared auth request',meCalls===1);
  const rows=page.locator('main dl');
  check('Real name and email',(await rows.innerText()).includes(user.name)&&(await rows.innerText()).includes(user.email));
  check('Real sign-in method',await rows.getByText('Email & password',{exact:true}).isVisible());
  check('Member date from API',!(await rows.innerText()).includes('Not available') && Boolean(user.created_at));
  check('No editable account fields',await page.locator('main input,main textarea').count()===0);
  const theme=page.getByRole('group',{name:'Theme preference'});
  for(const value of ['Dark','Light','System']) {
    await theme.getByRole('button',{name:value,exact:true}).click();
    check(`${value} selected`,await theme.getByRole('button',{name:value,exact:true}).getAttribute('aria-pressed')==='true');
    check(`${value} syncs header`,await page.getByRole('button',{name:`Color theme: ${value}`,exact:true}).isVisible());
    check(`${value} uses existing storage`,await page.evaluate(()=>localStorage.getItem('hf.theme'))===(value==='System'?null:value.toLowerCase()));
    await page.reload({waitUntil:'networkidle'});
    check(`${value} persists after reload`,await theme.getByRole('button',{name:value,exact:true}).getAttribute('aria-pressed')==='true');
  }
  await page.emulateMedia({colorScheme:'dark'});
  check('System follows dark OS',await page.evaluate(()=>getComputedStyle(document.documentElement).colorScheme)==='dark');
  await page.emulateMedia({colorScheme:'light'});
  await page.getByRole('button',{name:'Color theme: System',exact:true}).click();
  await page.getByRole('button',{name:'Dark',exact:true}).last().click();
  check('Header change syncs Settings',await theme.getByRole('button',{name:'Dark',exact:true}).getAttribute('aria-pressed')==='true');
  check('Free plan is static and honest',await page.locator('main').getByText('Free',{exact:true}).isVisible() && await page.getByText('Paid plans on the pricing page are previews.').isVisible());
  check('Pricing href preserved',await page.getByRole('link',{name:'View plan information'}).getAttribute('href')==='/pricing');
  check('No billing controls',await page.getByRole('button',{name:/checkout|upgrade|invoice|payment/i}).count()===0);
  await matrix(page,'settings');
  const longEmail='a'.repeat(64)+'@'+'long-domain.'.repeat(7)+'example.com';
  await page.route('**/api/auth/me',r=>r.fulfill({json:{user:{...user,email:longEmail,name:'A reader with a long account display name',has_password:false}}}));
  await page.reload({waitUntil:'networkidle'});
  check('Google sign-in from returned has_password',await page.locator('main dl').getByText('Google account').isVisible());
  await matrix(page,'settings-long');
  await page.unroute('**/api/auth/me');
  let release; const gate=new Promise(resolve=>{release=resolve;});
  await page.route('**/api/auth/me',async r=>{await gate;await r.continue();});
  await page.goto(base+'/settings',{waitUntil:'domcontentloaded'});
  await page.locator('[aria-busy=true][aria-label=Loading]').waitFor();
  check('Accessible session loading',true);
  await page.screenshot({path:`shots/settings-loading.png`.replace('shots',shots),fullPage:true});
  release(); await page.waitForLoadState('networkidle'); await page.unroute('**/api/auth/me');
  await page.route('**/api/auth/me',r=>r.fulfill({status:503,json:{detail:'Fixture unavailable'}}));
  await page.reload({waitUntil:'networkidle'});
  const sessionError=page.getByRole('heading',{name:"We couldn't verify your session"});
  await sessionError.waitFor({timeout:20000});
  check('Existing session error shown',await sessionError.isVisible());
  check('No fabricated data on error',await page.locator('main dl').count()===0);
  await page.screenshot({path:`${shots}/settings-error.png`,fullPage:true});
  await page.unroute('**/api/auth/me');await page.reload({waitUntil:'networkidle'});
  await page.getByRole('button',{name:'Log out',exact:true}).click(); await page.waitForURL(base+'/');await page.waitForLoadState('networkidle');
  check('Existing logout POST once',logoutCalls===1);
  check('Session revoked',(await (await context.request.get(base+'/api/auth/me')).json()).user===null);
  check('User cache cleared from shell',await page.getByRole('button',{name:new RegExp(user.name)}).count()===0);
  await goto(page,'/settings');check('Protected after logout',new URL(page.url()).pathname==='/login');
} finally { await finish(browser); }
