import type { LucideIcon } from "lucide-react";
import {
  AudioLines,
  Box,
  Camera,
  Clapperboard,
  Film,
  Image as ImageIcon,
  Languages,
  Layers,
  LayoutGrid,
  Mic,
  Palette,
  Paintbrush,
  Repeat,
  ScanFace,
  Scissors,
  Sparkles,
  SquareUser,
  UserRound,
  Video,
  Wand2,
  ZoomIn,
} from "lucide-react";

export type ToolCategory = "image" | "video" | "audio";

/**
 * `available` tools are backed by a real generator; `preview` tools reproduce the product
 * surface (a representative page) and point at the nearest working workflow.
 */
export type ToolStatus = "available" | "preview";

export interface Tool {
  slug: string;
  name: string;
  description: string;
  category: ToolCategory;
  icon: LucideIcon;
  status: ToolStatus;
  /** Destination for available tools (a generator, optionally with query presets). */
  href?: string;
  badge?: "New" | "Free" | "TOP";
  /** Longer copy for the representative tool page. */
  longDescription: string;
  steps: [string, string, string];
  /** Where a preview tool sends the user to do real work today. */
  fallbackHref: string;
  fallbackLabel: string;
  /** Deterministic photo seed for the tool's cover. */
  seed: string;
}

const IMAGE_TOOLS: Tool[] = [
  {
    slug: "create-image",
    name: "Create Image",
    description: "Generate AI images",
    category: "image",
    icon: ImageIcon,
    status: "available",
    href: "/generate/image",
    longDescription: "Describe a scene, character, mood or style and generate it with FLUX.1 Schnell, SDXL Lightning, Lucid Origin or FLUX.2 Klein.",
    steps: ["Describe the scene", "Pick a model and aspect ratio", "Generate up to four images"],
    fallbackHref: "/generate/image",
    fallbackLabel: "Create Image",
    seed: "create-image",
  },
  {
    slug: "edit-image",
    name: "Edit Image",
    description: "Reference-guided edits with FLUX.2 Klein",
    category: "image",
    icon: Wand2,
    status: "available",
    href: "/edit/image",
    longDescription: "Upload an image, describe the change and let FLUX.2 Klein re-render it with your instruction.",
    steps: ["Upload a reference", "Describe the change", "Generate the edit"],
    fallbackHref: "/edit/image",
    fallbackLabel: "Edit Image",
    seed: "edit-image",
  },
  {
    slug: "cinematic-cameras",
    name: "Cinematic Cameras",
    description: "Image generation with camera controls",
    category: "image",
    icon: Camera,
    status: "preview",
    badge: "TOP",
    longDescription: "Compose stills like a cinematographer: lens, focal length, camera height and movement presets baked into the prompt.",
    steps: ["Choose a camera and lens", "Frame the shot", "Generate the still"],
    fallbackHref: "/generate/image?model=lucid-origin&prompt=cinematic%2035mm%20portrait%2C%20shallow%20depth%20of%20field%2C%20anamorphic%20lens%20flare",
    fallbackLabel: "Try a cinematic prompt",
    seed: "cinematic-cameras",
  },
  {
    slug: "canvas",
    name: "Canvas",
    description: "Visual ideation meets repeatable AI workflows.",
    category: "image",
    icon: LayoutGrid,
    status: "preview",
    longDescription: "Moodboard, chain models and share with your team — all on one infinite canvas.",
    steps: ["Drop references onto the canvas", "Chain image and video nodes", "Run the workflow"],
    fallbackHref: "/canvas",
    fallbackLabel: "Open Canvas",
    seed: "canvas",
  },
  {
    slug: "ai-influencer",
    name: "AI Influencer",
    description: "Create and manage your AI influencer",
    category: "image",
    icon: UserRound,
    status: "preview",
    longDescription: "Design a persona, keep it consistent and produce a steady feed of posts, stories and clips.",
    steps: ["Design the persona", "Generate the look", "Publish a content calendar"],
    fallbackHref: "/generate/image",
    fallbackLabel: "Create Image",
    seed: "ai-influencer",
  },
  {
    slug: "photodump",
    name: "Photodump",
    description: "Generate Your Aesthetic",
    category: "image",
    icon: Sparkles,
    status: "preview",
    longDescription: "Different scenes, same star. Build your character and one click does the rest.",
    steps: ["Pick a character", "Choose a vibe", "Get a full photodump"],
    fallbackHref: "/generate/image?model=sdxl-lightning&prompt=candid%20film%20photo%20dump%2C%20golden%20hour%2C%20fashion%20editorial",
    fallbackLabel: "Try a photodump prompt",
    seed: "photodump",
  },
  {
    slug: "relight",
    name: "Relight",
    description: "Adjust lighting position, color, and brightness",
    category: "image",
    icon: Wand2,
    status: "preview",
    longDescription: "Move the key light, warm the fill and change the time of day without reshooting.",
    steps: ["Upload an image", "Describe the lighting", "Generate the relit version"],
    fallbackHref: "/edit/image",
    fallbackLabel: "Edit Image",
    seed: "relight",
  },
  {
    slug: "inpaint",
    name: "Inpaint",
    description: "Select an area, describe the change",
    category: "image",
    icon: Paintbrush,
    status: "preview",
    longDescription: "Paint over a region and describe what should be there instead.",
    steps: ["Upload an image", "Mask the area", "Describe the replacement"],
    fallbackHref: "/edit/image",
    fallbackLabel: "Edit Image",
    seed: "inpaint",
  },
  {
    slug: "image-upscale",
    name: "Image Upscale",
    description: "Enhance image quality",
    category: "image",
    icon: ZoomIn,
    status: "preview",
    longDescription: "Upscale generations to print resolution while keeping detail crisp.",
    steps: ["Upload an image", "Pick 2× or 4×", "Download the upscale"],
    fallbackHref: "/edit/image",
    fallbackLabel: "Edit Image",
    seed: "upscale",
  },
  {
    slug: "face-swap",
    name: "Face Swap",
    description: "Create Realistic Face Swaps",
    category: "image",
    icon: ScanFace,
    status: "preview",
    longDescription: "Swap a face into any image with matched lighting and skin tone.",
    steps: ["Upload the target", "Upload the face", "Generate the swap"],
    fallbackHref: "/edit/image",
    fallbackLabel: "Edit Image",
    seed: "face-swap",
  },
  {
    slug: "character-swap",
    name: "Character Swap",
    description: "Create Realistic Character Swaps",
    category: "image",
    icon: Repeat,
    status: "preview",
    longDescription: "Replace a whole character — outfit, pose and all — while keeping the scene intact.",
    steps: ["Upload the scene", "Choose the character", "Generate the swap"],
    fallbackHref: "/edit/image",
    fallbackLabel: "Edit Image",
    seed: "character-swap",
  },
];

const VIDEO_TOOLS: Tool[] = [
  {
    slug: "create-video",
    name: "Create Video",
    description: "Generate AI videos",
    category: "video",
    icon: Video,
    status: "available",
    href: "/generate/video",
    longDescription: "Turn a prompt or a still image into a short clip with LTX Video.",
    steps: ["Add an image or start from text", "Describe the motion", "Generate the clip"],
    fallbackHref: "/generate/video",
    fallbackLabel: "Create Video",
    seed: "create-video",
  },
  {
    slug: "cinema-studio",
    name: "Cinema Studio",
    description: "Cinematic video with AI director",
    category: "video",
    icon: Clapperboard,
    status: "preview",
    longDescription: "Camera, lens, lighting and multi-shot scenes with an AI director on every take.",
    steps: ["Set the camera and lens", "Light the scene", "Direct the shot"],
    fallbackHref: "/cinema-studio",
    fallbackLabel: "Open Cinema Studio",
    seed: "cinema-studio",
  },
  {
    slug: "faceless-studio",
    name: "Faceless Studio",
    description: "Start a faceless channel in one click",
    category: "video",
    icon: SquareUser,
    status: "preview",
    longDescription: "Scripts, voice-over and b-roll for channels that never show a face.",
    steps: ["Pick a niche", "Generate script and voice", "Render the episode"],
    fallbackHref: "/generate/audio",
    fallbackLabel: "Generate a voice-over",
    seed: "faceless",
  },
  {
    slug: "3d-jutsu",
    name: "Scene blocking",
    description: "Block out a 3D scene and turn it into video",
    category: "video",
    icon: Box,
    status: "preview",
    badge: "New",
    longDescription: "Block out a 3D scene, place the camera and render it into a cinematic clip.",
    steps: ["Build the scene", "Place the camera", "Render to video"],
    fallbackHref: "/3d-jutsu",
    fallbackLabel: "Open the scene blocking concept",
    seed: "3d-jutsu",
  },
  {
    slug: "shorts-studio",
    name: "Shorts Studio",
    description: "Turn your footage into ready-made shorts",
    category: "video",
    icon: Film,
    status: "preview",
    longDescription: "Cut long footage into vertical shorts with captions and hooks.",
    steps: ["Upload footage", "Pick the moments", "Export shorts"],
    fallbackHref: "/generate/video?aspect=9%3A16",
    fallbackLabel: "Create a vertical clip",
    seed: "shorts",
  },
  {
    slug: "canvas-video",
    name: "Canvas",
    description: "Visual ideation meets repeatable AI workflows.",
    category: "video",
    icon: LayoutGrid,
    status: "preview",
    longDescription: "Chain image and video generations on one canvas and share it with your team.",
    steps: ["Drop references", "Chain the nodes", "Run the workflow"],
    fallbackHref: "/canvas",
    fallbackLabel: "Open Canvas",
    seed: "canvas-video",
  },
  {
    slug: "mixed-media",
    name: "Mixed Media",
    description: "Create mixed media projects",
    category: "video",
    icon: Layers,
    status: "preview",
    longDescription: "Combine stills, clips and voice-over into one project timeline.",
    steps: ["Generate the pieces", "Arrange the timeline", "Export the project"],
    fallbackHref: "/history",
    fallbackLabel: "Open your assets",
    seed: "mixed-media",
  },
  {
    slug: "edit-video",
    name: "Edit Video",
    description: "Edit scenes, shots, elements",
    category: "video",
    icon: Scissors,
    status: "preview",
    longDescription: "Text-based edits to an existing clip: swap objects, restyle, change the weather.",
    steps: ["Upload a clip", "Describe the edit", "Generate the new version"],
    fallbackHref: "/generate/video",
    fallbackLabel: "Create Video",
    seed: "edit-video",
  },
  {
    slug: "click-to-ad",
    name: "Click to Ad",
    description: "Turn product URLs into video ads",
    category: "video",
    icon: Wand2,
    status: "preview",
    longDescription: "Paste a product link and get a scripted, shot and voiced ad.",
    steps: ["Paste a product URL", "Pick a template", "Generate the ad"],
    fallbackHref: "/marketing-studio",
    fallbackLabel: "Open Marketing Studio",
    seed: "click-to-ad",
  },
  {
    slug: "change-color-palette",
    name: "Change Color Palette",
    description: "Adjust color palette, tones, and overall mood",
    category: "video",
    icon: Palette,
    status: "preview",
    longDescription: "Grade a clip to a new palette — teal and orange, pastel, noir — in one pass.",
    steps: ["Upload a clip", "Pick a palette", "Generate the grade"],
    fallbackHref: "/generate/video",
    fallbackLabel: "Create Video",
    seed: "palette",
  },
];

const AUDIO_TOOLS: Tool[] = [
  {
    slug: "text-to-speech",
    name: "Text to Speech",
    description: "Generate speech from text",
    category: "audio",
    icon: Mic,
    status: "available",
    href: "/generate/audio",
    longDescription: "Lifelike speech from any script with Aura, MeloTTS or Gemini voices.",
    steps: ["Write the script", "Pick a voice", "Generate the take"],
    fallbackHref: "/generate/audio",
    fallbackLabel: "Text to Speech",
    seed: "tts",
  },
  {
    slug: "voice-change",
    name: "Voice Change",
    description: "Swap voices in any video",
    category: "audio",
    icon: AudioLines,
    status: "preview",
    longDescription: "Replace the voice in a clip while keeping timing and emotion.",
    steps: ["Upload a clip", "Pick a target voice", "Generate the swap"],
    fallbackHref: "/generate/audio",
    fallbackLabel: "Text to Speech",
    seed: "voice-change",
  },
  {
    slug: "translate",
    name: "Translate",
    description: "Translate and lip-sync your video into a new language",
    category: "audio",
    icon: Languages,
    status: "preview",
    longDescription: "Dub a clip into another language with matched lip movement.",
    steps: ["Upload a clip", "Choose the language", "Generate the dub"],
    fallbackHref: "/generate/audio?model=melotts",
    fallbackLabel: "Generate multilingual speech",
    seed: "translate",
  },
];

export const TOOLS: Tool[] = [...IMAGE_TOOLS, ...VIDEO_TOOLS, ...AUDIO_TOOLS];

export const toolsByCategory = (category: ToolCategory): Tool[] => TOOLS.filter((t) => t.category === category);

export const getTool = (slug: string): Tool | undefined => TOOLS.find((t) => t.slug === slug);

/** Link target for a tool: the generator when available, otherwise its representative page. */
export const toolHref = (tool: Tool): string => tool.href ?? `/tools/${tool.slug}`;
